"""Integration tests for the build pipeline (registry, build.py, check_links).

Import strategy mirrors the other tests: insert the absolute ``src`` directory
onto ``sys.path`` so ``import shell`` / ``import build`` work like production.
The build writes real files into the repo (committed deliverables); we build
once in ``setUpClass`` and assert against the generated artifacts.
"""

import os
import sys
import tempfile
import unittest

SRC = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.insert(0, SRC)

import shell  # noqa: E402
import registry  # noqa: E402
import build  # noqa: E402
import check_links  # noqa: E402
import i18n  # noqa: E402

ROOT = build.ROOT
ZH_PLACEHOLDER = "本课内容正在编写中。"
EN_PLACEHOLDER = "This lesson is being written."


class TestBuildPipeline(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.written = build.build()

    def test_data_parity(self):
        self.assertEqual(
            set(registry.CONTENT.keys()),
            {p.fname for p in shell.PAGES},
        )

    def test_build_produces_all_files(self):
        self.assertTrue(os.path.exists(os.path.join(ROOT, "index.html")))
        for p in shell.PAGES:
            self.assertTrue(
                os.path.exists(os.path.join(ROOT, "lessons", p.fname)),
                f"missing lessons/{p.fname}",
            )
        self.assertEqual(len(shell.PAGES), 24)
        # 24 lessons + index = 25 written files
        self.assertEqual(len(self.written), 25)

    def test_bilingual_integrity(self):
        for p in shell.PAGES:
            with open(os.path.join(ROOT, "lessons", p.fname), encoding="utf-8") as f:
                html = f.read()
            self.assertIn('class="zh"', html, p.fname)
            self.assertIn('class="en"', html, p.fname)
            self.assertIn('id="langbtn"', html, p.fname)
            self.assertIn("<!DOCTYPE html>", html, p.fname)

    def test_index_integrity(self):
        with open(os.path.join(ROOT, "index.html"), encoding="utf-8") as f:
            html = f.read()
        for p in shell.PAGES:
            self.assertIn(f'href="lessons/{p.fname}"', html)
        self.assertIn('id="langbtn"', html)
        # Index offers both bilingual PDF downloads (generated by the deploy CI).
        self.assertIn('href="generic-agent-visual-guide-zh.pdf"', html)
        self.assertIn('href="generic-agent-visual-guide-en.pdf"', html)

    def test_no_dead_links(self):
        checked, broken = check_links.check()
        self.assertEqual(broken, [], f"broken links: {broken}")
        self.assertGreater(checked, 0)

    def test_body_bilingual_all_pages(self):
        # Targets lesson BODY content (not just chrome) in a content-agnostic
        # way: render each lesson function through both i18n passes and assert
        # both renders are non-empty AND differ. Differing output proves the
        # lesson actually routed prose through t(...). This holds for the real
        # lessons (01-03) and the remaining stubs (04-23) alike.
        for fname, fn in registry.CONTENT.items():
            zh = fn(i18n.t_zh)
            en = fn(i18n.t_en)
            self.assertTrue(zh.strip(), f"{fname}: empty zh render")
            self.assertTrue(en.strip(), f"{fname}: empty en render")
            self.assertNotEqual(
                zh, en, f"{fname}: zh and en renders identical (missing t(...)?)"
            )

    def test_stale_file_cleanup(self):
        junk = os.path.join(ROOT, "lessons", "99-junk.html")
        with open(junk, "w", encoding="utf-8") as f:
            f.write("<!-- junk -->")
        self.assertTrue(os.path.exists(junk))
        build.build()
        self.assertFalse(os.path.exists(junk), "stale 99-junk.html not removed")
        for p in shell.PAGES:
            self.assertTrue(
                os.path.exists(os.path.join(ROOT, "lessons", p.fname)),
                f"missing lessons/{p.fname} after rebuild",
            )

    def test_stub_render_through_pipeline(self):
        # Verifies a still-stub lesson renders both i18n passes end-to-end
        # through the build pipeline. As lessons gain real content this picks
        # any REMAINING stub dynamically; once all 23 are written it skips.
        stub_fname = next(
            (p.fname for p in shell.PAGES
             if EN_PLACEHOLDER in registry.CONTENT[p.fname](i18n.t_en)),
            None,
        )
        if stub_fname is None:
            self.skipTest("no stub lessons remain")
        with open(os.path.join(ROOT, "lessons", stub_fname), encoding="utf-8") as f:
            html = f.read()
        zh = html.split('<div class="zh">', 1)[1].split('<div class="en">', 1)[0]
        en = html.split('<div class="en">', 1)[1]
        self.assertIn(ZH_PLACEHOLDER, zh)
        self.assertIn(EN_PLACEHOLDER, en)


    def test_completed_lessons_follow_card_format(self):
        # Validates the 5-card template for every COMPLETED tutorial lesson and
        # auto-skips stubs, so it scales to all lessons with no future edits.
        # The glossary (24) is a reference/index page, not a 5-card tutorial,
        # so it is intentionally exempt.
        required = ['card macro', 'card detail', 'card analogy', 'card key', 'card spark']
        EXEMPT = {'24-glossary.html'}
        for fname, fn in registry.CONTENT.items():
            if fname in EXEMPT:
                continue
            en = fn(i18n.t_en)
            if EN_PLACEHOLDER in en:
                continue  # still a stub; skip
            zh = fn(i18n.t_zh)
            self.assertIn('class="lead"', zh, f"{fname}: missing lead paragraph")
            for cls in required:
                self.assertIn(cls, zh, f"{fname}: missing {cls} card")

    # Lessons confirmed "deepened" (≥2 deep-dive accordions). Grows as each
    # lesson is thickened; keeps the suite green between per-lesson commits
    # while enforcing the depth contract on completed lessons.
    DEEPENED = {'01-what-is-ga.html', '02-project-map.html', '03-task-lifecycle.html',
                '04-install.html', '05-frontends.html', '06-commands.html', '07-tools.html',
                '08-agent-loop.html', '09-llmcore.html', '10-handler-dispatch.html',
                '11-layered-memory.html', '12-memory-crystallize.html',
                '13-hooks-observability.html', '14-context-tokens.html',
                '15-vision.html', '16-input-mobile.html', '17-browser.html',
                '18-reflect-orchestration.html', '19-autonomy.html',
                '20-self-evolution.html', '21-build-a-skill.html', '22-extend-frontend.html',
                '23-evaluation.html'}

    def test_deepened_lessons_have_accordions(self):
        # Every deepened tutorial lesson must carry >= 2 deep-dive accordions.
        for fname in self.DEEPENED:
            zh = registry.CONTENT[fname](i18n.t_zh)
            self.assertGreaterEqual(
                zh.count('class="accordion"'), 2,
                f"{fname}: expected >= 2 deep-dive accordions",
            )

    def test_all_pages_html_balanced(self):
        # Every built page must have balanced (void-aware) HTML tags.
        from html.parser import HTMLParser
        void = {'area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input',
                'link', 'meta', 'param', 'source', 'track', 'wbr'}

        class _Bal(HTMLParser):
            def __init__(self):
                super().__init__()
                self.stack, self.err = [], []

            def handle_starttag(self, tag, attrs):
                if tag not in void:
                    self.stack.append(tag)

            def handle_endtag(self, tag):
                if tag in void:
                    return
                if not self.stack or self.stack[-1] != tag:
                    self.err.append(tag)
                else:
                    self.stack.pop()

        pages = [os.path.join(ROOT, "index.html")] + [
            os.path.join(ROOT, "lessons", p.fname) for p in shell.PAGES
        ]
        for path in pages:
            with open(path, encoding="utf-8") as f:
                p = _Bal()
                p.feed(f.read())
            self.assertEqual(p.stack, [], f"{os.path.basename(path)}: unclosed {p.stack[-3:]}")
            self.assertEqual(p.err, [], f"{os.path.basename(path)}: stray closes {p.err[:3]}")


class TestCheckLinksAnchors(unittest.TestCase):
    """Unit-style tests for anchor-aware check_links.check(root=...)."""

    def _build_site(self, root, index_html, lesson_html):
        os.makedirs(os.path.join(root, "lessons"), exist_ok=True)
        with open(os.path.join(root, "index.html"), "w", encoding="utf-8") as f:
            f.write(index_html)
        with open(os.path.join(root, "lessons", "a.html"), "w", encoding="utf-8") as f:
            f.write(lesson_html)

    def test_anchors_resolve(self):
        with tempfile.TemporaryDirectory() as root:
            self._build_site(
                root,
                index_html=(
                    '<a id="top"></a>'
                    '<a href="#top">self</a>'
                    '<a href="lessons/a.html#sec">cross</a>'
                ),
                lesson_html='<h2 id="sec">Section</h2>',
            )
            checked, broken = check_links.check(root=root)
            self.assertEqual(broken, [], f"unexpected broken: {broken}")
            self.assertGreater(checked, 0)

    def test_anchors_broken(self):
        with tempfile.TemporaryDirectory() as root:
            self._build_site(
                root,
                index_html=(
                    '<a id="top"></a>'
                    '<a href="#missing">bad self</a>'
                    '<a href="lessons/a.html#missing">bad cross</a>'
                ),
                lesson_html='<h2 id="sec">Section</h2>',
            )
            checked, broken = check_links.check(root=root)
            self.assertGreater(len(broken), 0)
            hrefs = {href for _, href, _ in broken}
            self.assertIn("#missing", hrefs)
            self.assertIn("lessons/a.html#missing", hrefs)
            for _, _, reason in broken:
                self.assertIn("missing anchor", reason)

    def test_missing_file_reason(self):
        with tempfile.TemporaryDirectory() as root:
            self._build_site(
                root,
                index_html='<a href="lessons/nope.html">gone</a>',
                lesson_html="<p>ok</p>",
            )
            checked, broken = check_links.check(root=root)
            self.assertTrue(
                any(reason == "missing file" for _, _, reason in broken),
                f"expected a missing-file reason, got {broken}",
            )


class TestAccessibility(unittest.TestCase):
    """Regression tests for the accessibility fixes (heading outline, landmarks,
    plain-text aria-labels). Each fix originates in ``shell.py`` / the lesson
    generators, so these guard every built page at once."""

    @classmethod
    def setUpClass(cls):
        build.build()
        cls.pages = {
            "index.html": os.path.join(ROOT, "index.html"),
            **{p.fname: os.path.join(ROOT, "lessons", p.fname) for p in shell.PAGES},
        }

    @staticmethod
    def _headings(html):
        import re
        return [int(h) for h in re.findall(r"<h([1-6])\b", html)]

    def test_no_heading_level_skips(self):
        # Screen-reader outline (WCAG 1.3.1): a heading may go one level deeper
        # at a time only (h2 -> h3, never h2 -> h4).
        for name, path in self.pages.items():
            with open(path, encoding="utf-8") as f:
                levels = self._headings(f.read())
            prev = 0
            for h in levels:
                if prev:
                    self.assertLessEqual(
                        h, prev + 1, f"{name}: heading jumps {prev}->{h} (skips a level)"
                    )
                prev = h

    def test_semantic_landmarks_present(self):
        # Interactive pages expose <header>, <main> and a labelled <nav>.
        for name, path in self.pages.items():
            with open(path, encoding="utf-8") as f:
                s = f.read()
            self.assertIn('<header class="topbar">', s, f"{name}: no <header>")
            self.assertIn('<main class="wrap">', s, f"{name}: no <main>")
            self.assertIn("</main>", s, f"{name}: unclosed <main>")
            if name == "index.html":
                self.assertIn('<nav class="toc"', s, f"{name}: no toc <nav>")
            else:
                self.assertIn('<nav class="footnav"', s, f"{name}: no footnav <nav>")

    def test_aria_labels_are_plain_text(self):
        # Regression: aria-label values must be plain text, never bi()/markup
        # (a '<' inside an attribute corrupts parsing).
        import re
        for name, path in self.pages.items():
            with open(path, encoding="utf-8") as f:
                s = f.read()
            for val in re.findall(r'aria-label="([^"]*)"', s):
                self.assertNotIn("<", val, f"{name}: markup leaked into aria-label: {val!r}")



